### ISSUE TITLE
Launch WhatsApp with image 

### ISSUE THREAD

**Issue by Amitpatil215** [dartsidedev/whatsapp_unilink#2]
Thanks for this amazing package 💜 

How can I launch WhatsApp along with image and text? is there any workaround for this or if u are planning to add this feature in this package? Thanks in advance!

**Comment by mohadel92** [comment]
same question

**Comment by Amitpatil215** [comment]
@mohadel92 https://pub.dev/packages/whatsapp_share

**Comment by vincevargadev** [comment]
This package aims to provide a convenient wrapper for WhatsApp **unilinks**, and images are not supported by WhatsApp's universal links. Therefore, this package also cannot support images (without completely rethinking the package and expanding its scope). I'm not planning to add image support to this package. 

* [WhatsApp FAQ > Android > How to use click to chat](https://faq.whatsapp.com/en/android/26000030/)
* [WhatsApp FAQ > iPhone > How to link to WhatsApp from a different app](https://faq.whatsapp.com/en/iphone/23559013)

@Amitpatil215 Thank you for linking to the plugin. I'm glad you could create your own plugin to solve the issue and that you made it open source.
