### ISSUE TITLE
Add Images

### ISSUE THREAD

**Issue by ranahyder87** [dartsidedev/whatsapp_unilink#4]
Hello, this is related to "improvement"

This is very good, neat, and clean WhatsApp sharing to a specific phone number.

If the image attachment can be added to it then it will be more useful and more perfect.

**Comment by ghost** [comment]
Agree . Images will improve this package.

**Comment by vincevargadev** [comment]
For more info, here: https://github.com/dartsidedev/whatsapp_unilink/issues/2#issuecomment-968364271
