### ISSUE TITLE
Query about sending a message to a Watsapp group.

### ISSUE THREAD

**Issue by B1ZOT1C** [dartsidedev/whatsapp_unilink#5]
I was wondering if it is possible in any way to send a message to a Watsapp group instead of sending it to an individual number.
If so how and what changes should I make? @vincevargadev

**Comment by vincevargadev** [comment]
I'm closing this issue because as far as I know, this is not supported by WhatsApp. Unilinks only support a phone number and a message (both optional).

If you come up with any workaround, please share it here on this issue, maybe someone else will be interested, too.
