### ISSUE TITLE
launchUrl method fail

### ISSUE THREAD

**Issue by moisesbinzie** [dartsidedev/whatsapp_unilink#7]
Now that the Url_laucher launch() method is deprecated, it's suggesting the use of "launchUrl" method, which is failing to launch whatsapp. I am using url_launcher 6.1.2.

My code looks like this;

    final link = WhatsAppUnilink(
                     phoneNumber: '+265123456789', text: ' Test message');

                       // Convert the WhatsAppUnilink instance to a string.
                       // Use either Dart's string interpolation or the toString
                      // The "launch" method is part of "url_launcher".

                   await launchUrl(Uri.parse('$link'));

Url_ launcher package has also been imported. Help

**Comment by enzo-santos** [comment]
What do you mean by "failing to launch"? Is it throwing an error or not doing anything at all?

**Comment by moisesbinzie** [comment]
The problem is that it's trying to launch whatsapp on web, which still fails to do so. previously, it was launching the whatsapp app. 

**- The Android Emulator shows** on windows pc

**Webpage not available**
The webpage at whatsapp://send/?phone=26588*****41&text=hey!

could not be loaded because:
net: ERR_UNKNOWN_URL_SCHEME


**-The Debug console shows the following**

D/skia    (13640): link failed but did not provide an info log
I/WebViewFactory(17391): Loading com.google.android.webview version 91.0.4472.114 (code 447211487)
D/skia    (13640): Shader compilation error
W/om.debantu.get(17391): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
W/om.debantu.get(17391): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
W/om.debantu.get(17391): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
W/om.debantu.get(17391): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
W/om.debantu.get(17391): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
I/cr_LibraryLoader(17391): Loaded native library version number "91.0.4472.114"
I/cr_CachingUmaRecorder(17391): Flushed 6 samples from 6 histograms.
D/CompatibilityChangeReporter(17391): Compat change id reported: 171228096; UID 10151; state: ENABLED
W/om.debantu.get(17391): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
D/HostConnection(17391): createUnique: call
D/HostConnection(17391): HostConnection::get() New Host Connection established 0x7b44517c3850, tid 17540
W/cr_media(17391): Requires BLUETOOTH permission
D/HostConnection(17391): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0

**Comment by dumabg** [comment]
url_launcher analyzes the url. If starts with http, it selects to launch the url in a WebView, and this error appears (on iPhone has the same problem).

If put the mode in url_launcher to externalApplication, it works.

`await launchUrlString(link.toString(),
        mode: LaunchMode.externalApplication);`

**Comment by moisesbinzie** [comment]
hurray!!! it works... 

I hope you will include the above method in your package documentation. The current documentation shows a deprecated method.
Thanks for the help,  and for the Package....

**Comment by oguzyildiz1991** [comment]
I'm having this problem in Android, works fine in iPhones. I tried using the other LaunchMode enums, didn't work. Any other suggestions?
