### ISSUE TITLE
webview_flutter violates content security policy

### ISSUE THREAD

**Issue by KelvinEng1215** [dartsidedev/whatsapp_unilink#8]
Android open WhatsApp's link will prompt error below
[INFO:CONSOLE(29)] "Refused to load the font 'https://static.whatsapp.net/rsrc.php/yR/r/_gCoI-iROin.woff' because it violates the following Content Security Policy directive: "font-src data: https://*.fbcdn.net".

**Comment by vincevargadev** [comment]
I'm not quite sure if this is an issue on the Dart package's part. I'm not controlling which fonts are used and how by WhatsApp.
